#!/usr/bin/env python3

import subprocess
import notify2

def main():
    notify2.init("perfctl")

    list_profiles = subprocess.run(["powerprofilesctl", "list"], capture_output=True, text=True)
    profiles = []
    for line in list_profiles.stdout.splitlines():
        line = line.strip()
        if line.endswith(":") and not any(word in line for word in ["Driver", "Degraded"]):
            profiles.append(line.replace(":", "").replace("*", "").strip())

    current_profiles = subprocess.run(["powerprofilesctl", "get"], capture_output=True, text=True).stdout
    next_profile_index = profiles.index(current_profiles.strip()) + 1

    if 0 <= next_profile_index < len(profiles):
        subprocess.run(["powerprofilesctl", "set",f"{profiles[next_profile_index]}"], capture_output=True, text=True)
        notify_message = notify2.Notification("Power Profile", f"Профиль производительности был изменен на {profiles[next_profile_index]}", "battery")
        notify_message.set_timeout(1000)
        notify_message.show()
        print(f"Профиль производительности был изменен на {profiles[next_profile_index]}")
    else:
        subprocess.run(["powerprofilesctl", "set",f"{profiles[0]}"], capture_output=True, text=True)
        notify_message = notify2.Notification("Power Profile", f"Профиль производительности был изменен на {profiles[0]}", "battery")
        notify_message.set_timeout(1000)
        notify_message.show()
        print(f"Профиль производительности был изменен на {profiles[0]}")

if __name__ == "__main__":
    main()
